### ISSUE TITLE
Yao::Server.listが返すimageは空の文字列を返すことがある

### ISSUE THREAD

**Issue by buty4649** [yaocloud/yao#136]
Yao::Server.listで一覧を取得したときに、imageが空の文字列を返すインスタンスがいる(e.g.  [ボリュームからのインスタンスの起動](https://docs.openstack.org/ja/user-guide/cli-nova-launch-instance-from-volume.html))
このYao::Serverインスタンスについてimageメソッドで情報を取得すると、空文字から生成Yao::Imageが返ってくる。

```
[64] yao(main)> sv.select{|s| s["image"] == ""}.first["image"]
=> ""
[65] yao(main)> sv.select{|s| s["image"] == ""}.first.image
=> #<Yao::Resources::Image:0x00005623da729c38 @data="">
```

imageを使用していないインスタンスか判定するときにこれでは不便なので、`nil`が返ってきてほしい。

**Comment by n01e0** [comment]
```console
[1] yao(main)> s = Yao::Server.new("image"=>"")
=> #<Yao::Resources::Server:0x00007febe48cb388 @data={"image"=>""}>
[2] yao(main)> s.image
=> nil
```

期待している挙動はこんな感じですか?

**Comment by buty4649** [comment]
@n01e0 そのとおりです！
