### ISSUE TITLE
Yao::Image.get(image_id)がnilになる

### ISSUE THREAD

**Issue by n01e0** [yaocloud/yao#161]
存在するイメージのIDを渡して`Yao::Image.get(image_id)`をしても
`#<Yao::Resources::Image:0x00007fda760e7f88 @data=nil>`
となり，期待通りのレスポンスが得られない．

**Comment by n01e0** [comment]
`get`内でレスポンスの取得には成功しているが，`res.body`から`resource_from_json`でインスタンスを生成する際，`res.body["image"]`が存在しない為，`data=nil`なインスタンスが生成されてしまう．

**Comment by buty4649** [comment]
あらま。。手元で確認したけど再現した。
API見ても `res.body["image"]` を返さないようだねぇ…。
https://docs.openstack.org/api-ref/image/v2/index.html?expanded=show-image-detail#images

**Comment by buty4649** [comment]
`Yao::Resource::RestfullyAccesible#resource_from_json` をオーバーロードして、res.bodyをそのまま返すようにするのがいいのかな？ :thinking:

**Comment by buty4649** [comment]
@hiboma どうでしょうか〜？

**Comment by n01e0** [comment]
https://github.com/yaocloud/yao/pull/162
とりあえずres.bodyをそのまま返すようにしてみました．

**Comment by buty4649** [comment]
fixed #162
