### ISSUE TITLE
Adding test mode

### ISSUE THREAD

**Issue by udzura** [yaocloud/yao#27]
Before adding this mode, we must think about:

* What kind of features is needed in test mode?
* How is the syntax?

**Comment by Joe-noh** [comment]
I think we need not only test mode but also read only mode.
It is useful to write `dryrun` code concisely.

I propose following syntax.

- `Yao.mock do ... end`
  - Does nothing and returns mock object or something.
- `Yao.read_only do ... end`
  - allow us to issue GET requests.
  - ignore all writing operations.
- `Yao.read_only! do ... end`
  - allow us to issue GET requests.
  - raise on writing operations.

**Comment by udzura** [comment]
> `Yao.read_only`

I want this too for [stackspec](https://github.com/yaocloud/stackspec).
Ideas(including raise/ign switch by `!`) seem nice!

**Comment by udzura** [comment]
Release 0.2.8 with this!
